# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate async-trait

Name:           rust-%{crate}
Version:        0.1.24
Release:        1%{?dist}
Summary:        Type erasure for async trait methods

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/async-trait
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Type erasure for async trait methods.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+support_old_nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+support_old_nightly-devel %{_description}

This package contains library source intended for building other packages
which use "support_old_nightly" feature of "%{crate}" crate.

%files       -n %{name}+support_old_nightly-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Feb 10 2020 Josh Stone <jistone@redhat.com> - 0.1.24-1
- Update to 0.1.24

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.21-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Sat Dec 14 14:03:56 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.21-1
- Initial package
